name: foodflow
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - azure-functions
      - azure-data-tables
      - azure-storage-blob
      - pydantic
      - requests
      - curl-cffi